name = "PrecomputedCaches"
uuid = "f61ad5e5-e0e7-4fc5-bbe8-3a0f67e781af"
authors = ["Shep Bryan IV <jsbryan4@asu.edu> and contributors"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"